config/routes.rb
Rails.application.routes.draw do
  root :to => "calorie_modifiers#index"
  resources :calorie_modifiers
end

app/models/calorie_modifier.rb
class CalorieModifier < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :calories
  validates_inclusion_of :is_intake, :in => [true, false]
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calorie_modifiers_controller.rb
class CalorieModifiersController < ApplicationController
  def index
    sleep
    @calorie_modifiers = CalorieModifier.order('calories').page(params[:page]).per_page(5)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @calorie_modifier = CalorieModifier.new
  end

  def create
    @calorie_modifier = CalorieModifier.new(calorie_modifier_params)
    if @calorie_modifier.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      render :new
    end
  end

  def destroy
    @calorie_modifier = CalorieModifier.find(params[:id])
    @calorie_modifier.destroy
    redirect_to root_path
  end

  private
  def calorie_modifier_params
    params.require(:calorie_modifier).permit(:is_intake, :name, :calories)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calorie_modifiers/_calorie_modifier.html.erb
<ul>
  <% @calorie_modifiers.each do |calorie_modifier| %>
    <% if calorie_modifier.is_intake %>
      <li>
        <%= calorie_modifier.name %>: <%= calorie_modifier.calories %> calories
        <%= link_to "(x)", calorie_modifier, method: :delete, data: {confirm: "Are you sure?"} %>
      </li>
    <% else %>
      <li>
        <%= calorie_modifier.name %>: -<%= calorie_modifier.calories %> calories
        <%= link_to "(x)", calorie_modifier, method: :delete, data: {confirm: "Are you sure?"} %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/calorie_modifiers/_form.html.erb
<%= simple_form_for(@calorie_modifier), :url => questions_path, :html => { :multipart => true }, :remote => true, :authenticity_token => true do |f| %>
  <%= f.collection_radio_buttons :is_intake, [[true, 'Yes'], [false, 'No']], :first, :last %>
  <%= f.input :name %>
  <%= f.input :calories %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/calorie_modifiers/create.js.erb
$('#new_calorie_modifier').remove();
$('#edit_question_<%= @question.id %>').submitOnClick();

app/views/calorie_modifiers/index.html.erb
<h1>Health Tracker</h1>

<div id="entry_form"></div>

<div id="calorie_modifiers">
  <!-- Using a partial here will create issues with will_paginate: -->
  <ul>
    <% @calorie_modifiers.each do |calorie_modifier| %>
      <% if calorie_modifier.is_intake %>
        <li>
          <%= calorie_modifier.name %>: <%= calorie_modifier.calories %> calories
          <%= link_to "(x)", calorie_modifier, method: :delete, data: {confirm: "Are you sure?"} %>
        </li>
      <% else %>
        <li>
          <%= calorie_modifier.name %>: -<%= calorie_modifier.calories %> calories
          <%= link_to "(x)", calorie_modifier, method: :delete, data: {confirm: "Are you sure?"} %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>


<%= will_paginate @calorie_modifiers %>

app/views/calorie_modifiers/index.js.erb
$('#calorie_modifiers').append('<%= j render(@calorie_modifiers) %>');
<% if @calorie_modifiers.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@calorie_modifiers) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/calorie_modifiers/new.html.erb
<h1>Enter in your intake/outake:</h1>

<%= render 'form' %>

app/views/calorie_modifiers/new.js.erb
$('#new_calorie_modifier').remove();
$('<%= j render("form") %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse" id="my-navbar">
    <div class="container">
      <div class="navbar-header">

        <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a href="/" class="navbar-brand">Health Tracker</a>

      </div>
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav">
            <li><%= link_to "New Entry", new_calorie_modifier_path, remote: true %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>